/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MateriaPostIdImport } from './routes/materia.$postId'
import { Route as AlunoPostIdImport } from './routes/aluno.$postId'

// Create Virtual Routes

const MateriasLazyImport = createFileRoute('/materias')()
const HomeLazyImport = createFileRoute('/home')()
const BoletimLazyImport = createFileRoute('/boletim')()
const AlunosLazyImport = createFileRoute('/alunos')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MateriasLazyRoute = MateriasLazyImport.update({
  path: '/materias',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/materias.lazy').then((d) => d.Route))

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const BoletimLazyRoute = BoletimLazyImport.update({
  path: '/boletim',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/boletim.lazy').then((d) => d.Route))

const AlunosLazyRoute = AlunosLazyImport.update({
  path: '/alunos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/alunos.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MateriaPostIdRoute = MateriaPostIdImport.update({
  path: '/materia/$postId',
  getParentRoute: () => rootRoute,
} as any)

const AlunoPostIdRoute = AlunoPostIdImport.update({
  path: '/aluno/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosLazyImport
      parentRoute: typeof rootRoute
    }
    '/boletim': {
      id: '/boletim'
      path: '/boletim'
      fullPath: '/boletim'
      preLoaderRoute: typeof BoletimLazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasLazyImport
      parentRoute: typeof rootRoute
    }
    '/aluno/$postId': {
      id: '/aluno/$postId'
      path: '/aluno/$postId'
      fullPath: '/aluno/$postId'
      preLoaderRoute: typeof AlunoPostIdImport
      parentRoute: typeof rootRoute
    }
    '/materia/$postId': {
      id: '/materia/$postId'
      path: '/materia/$postId'
      fullPath: '/materia/$postId'
      preLoaderRoute: typeof MateriaPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/alunos': typeof AlunosLazyRoute
  '/boletim': typeof BoletimLazyRoute
  '/home': typeof HomeLazyRoute
  '/materias': typeof MateriasLazyRoute
  '/aluno/$postId': typeof AlunoPostIdRoute
  '/materia/$postId': typeof MateriaPostIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/alunos': typeof AlunosLazyRoute
  '/boletim': typeof BoletimLazyRoute
  '/home': typeof HomeLazyRoute
  '/materias': typeof MateriasLazyRoute
  '/aluno/$postId': typeof AlunoPostIdRoute
  '/materia/$postId': typeof MateriaPostIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/alunos': typeof AlunosLazyRoute
  '/boletim': typeof BoletimLazyRoute
  '/home': typeof HomeLazyRoute
  '/materias': typeof MateriasLazyRoute
  '/aluno/$postId': typeof AlunoPostIdRoute
  '/materia/$postId': typeof MateriaPostIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/boletim'
    | '/home'
    | '/materias'
    | '/aluno/$postId'
    | '/materia/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/boletim'
    | '/home'
    | '/materias'
    | '/aluno/$postId'
    | '/materia/$postId'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/boletim'
    | '/home'
    | '/materias'
    | '/aluno/$postId'
    | '/materia/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AlunosLazyRoute: typeof AlunosLazyRoute
  BoletimLazyRoute: typeof BoletimLazyRoute
  HomeLazyRoute: typeof HomeLazyRoute
  MateriasLazyRoute: typeof MateriasLazyRoute
  AlunoPostIdRoute: typeof AlunoPostIdRoute
  MateriaPostIdRoute: typeof MateriaPostIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AlunosLazyRoute: AlunosLazyRoute,
  BoletimLazyRoute: BoletimLazyRoute,
  HomeLazyRoute: HomeLazyRoute,
  MateriasLazyRoute: MateriasLazyRoute,
  AlunoPostIdRoute: AlunoPostIdRoute,
  MateriaPostIdRoute: MateriaPostIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/alunos",
        "/boletim",
        "/home",
        "/materias",
        "/aluno/$postId",
        "/materia/$postId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/alunos": {
      "filePath": "alunos.lazy.tsx"
    },
    "/boletim": {
      "filePath": "boletim.lazy.tsx"
    },
    "/home": {
      "filePath": "home.lazy.tsx"
    },
    "/materias": {
      "filePath": "materias.lazy.tsx"
    },
    "/aluno/$postId": {
      "filePath": "aluno.$postId.tsx"
    },
    "/materia/$postId": {
      "filePath": "materia.$postId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
